spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  properties:
#    hibernate:
#      format_sql: true
#      use_sql_comments: true
#      show_sql: true

#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: trace

server:
  port: 8082